// Code generated by "stringer -type=Engine"; DO NOT EDIT.

package dbee

import "strconv"

const _Engine_name = "Bolt"

var _Engine_index = [...]uint8{0, 4}

func (i Engine) String() string {
	i -= 1
	if i < 0 || i >= Engine(len(_Engine_index)-1) {
		return "Engine(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Engine_name[_Engine_index[i]:_Engine_index[i+1]]
}
