// Code generated by protoc-gen-go. DO NOT EDIT.
// source: index.proto

package schema

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IndexSlice struct {
	IDIndexes            [][]byte `protobuf:"bytes,1,rep,name=IDIndexes,proto3" json:"IDIndexes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexSlice) Reset()         { *m = IndexSlice{} }
func (m *IndexSlice) String() string { return proto.CompactTextString(m) }
func (*IndexSlice) ProtoMessage()    {}
func (*IndexSlice) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_087da7e1bb374d12, []int{0}
}
func (m *IndexSlice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexSlice.Unmarshal(m, b)
}
func (m *IndexSlice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexSlice.Marshal(b, m, deterministic)
}
func (dst *IndexSlice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexSlice.Merge(dst, src)
}
func (m *IndexSlice) XXX_Size() int {
	return xxx_messageInfo_IndexSlice.Size(m)
}
func (m *IndexSlice) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexSlice.DiscardUnknown(m)
}

var xxx_messageInfo_IndexSlice proto.InternalMessageInfo

func (m *IndexSlice) GetIDIndexes() [][]byte {
	if m != nil {
		return m.IDIndexes
	}
	return nil
}

func init() {
	proto.RegisterType((*IndexSlice)(nil), "schema.IndexSlice")
}

func init() { proto.RegisterFile("index.proto", fileDescriptor_index_087da7e1bb374d12) }

var fileDescriptor_index_087da7e1bb374d12 = []byte{
	// 81 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcc, 0x4b, 0x49,
	0xad, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0x54,
	0xd2, 0xe2, 0xe2, 0xf2, 0x04, 0x09, 0x07, 0xe7, 0x64, 0x26, 0xa7, 0x0a, 0xc9, 0x70, 0x71, 0x7a,
	0xba, 0x80, 0xf9, 0xa9, 0xc5, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0x3c, 0x41, 0x08, 0x81, 0x24, 0x36,
	0xb0, 0x56, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x53, 0xa5, 0x01, 0xda, 0x49, 0x00, 0x00,
	0x00,
}
