// Code generated by protoc-gen-go. DO NOT EDIT.
// source: set.proto

package schema

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Set struct {
	// repeated Partition partition = 1;
	Partitions           map[string]*Partition `protobuf:"bytes,1,rep,name=partitions,proto3" json:"partitions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Set) Reset()         { *m = Set{} }
func (m *Set) String() string { return proto.CompactTextString(m) }
func (*Set) ProtoMessage()    {}
func (*Set) Descriptor() ([]byte, []int) {
	return fileDescriptor_set_416f4610f3520f4b, []int{0}
}
func (m *Set) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Set.Unmarshal(m, b)
}
func (m *Set) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Set.Marshal(b, m, deterministic)
}
func (dst *Set) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Set.Merge(dst, src)
}
func (m *Set) XXX_Size() int {
	return xxx_messageInfo_Set.Size(m)
}
func (m *Set) XXX_DiscardUnknown() {
	xxx_messageInfo_Set.DiscardUnknown(m)
}

var xxx_messageInfo_Set proto.InternalMessageInfo

func (m *Set) GetPartitions() map[string]*Partition {
	if m != nil {
		return m.Partitions
	}
	return nil
}

type Partition struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Index                string   `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	Store                string   `protobuf:"bytes,3,opt,name=store,proto3" json:"store,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Partition) Reset()         { *m = Partition{} }
func (m *Partition) String() string { return proto.CompactTextString(m) }
func (*Partition) ProtoMessage()    {}
func (*Partition) Descriptor() ([]byte, []int) {
	return fileDescriptor_set_416f4610f3520f4b, []int{1}
}
func (m *Partition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partition.Unmarshal(m, b)
}
func (m *Partition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partition.Marshal(b, m, deterministic)
}
func (dst *Partition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partition.Merge(dst, src)
}
func (m *Partition) XXX_Size() int {
	return xxx_messageInfo_Partition.Size(m)
}
func (m *Partition) XXX_DiscardUnknown() {
	xxx_messageInfo_Partition.DiscardUnknown(m)
}

var xxx_messageInfo_Partition proto.InternalMessageInfo

func (m *Partition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Partition) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Partition) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

func init() {
	proto.RegisterType((*Set)(nil), "schema.Set")
	proto.RegisterMapType((map[string]*Partition)(nil), "schema.Set.PartitionsEntry")
	proto.RegisterType((*Partition)(nil), "schema.Partition")
}

func init() { proto.RegisterFile("set.proto", fileDescriptor_set_416f4610f3520f4b) }

var fileDescriptor_set_416f4610f3520f4b = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x4e, 0x2d, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0x54, 0x9a, 0xc2,
	0xc8, 0xc5, 0x1c, 0x9c, 0x5a, 0x22, 0x64, 0xcd, 0xc5, 0x55, 0x90, 0x58, 0x54, 0x92, 0x59, 0x92,
	0x99, 0x9f, 0x57, 0x2c, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0x24, 0xad, 0x07, 0x51, 0xa4, 0x17,
	0x9c, 0x5a, 0xa2, 0x17, 0x00, 0x97, 0x75, 0xcd, 0x2b, 0x29, 0xaa, 0x0c, 0x42, 0x52, 0x2e, 0x15,
	0xc0, 0xc5, 0x8f, 0x26, 0x2d, 0x24, 0xc0, 0xc5, 0x9c, 0x9d, 0x5a, 0x29, 0xc1, 0xa8, 0xc0, 0xa8,
	0xc1, 0x19, 0x04, 0x62, 0x0a, 0xa9, 0x73, 0xb1, 0x96, 0x25, 0xe6, 0x94, 0xa6, 0x4a, 0x30, 0x29,
	0x30, 0x6a, 0x70, 0x1b, 0x09, 0xc2, 0x0c, 0x87, 0xeb, 0x0c, 0x82, 0xc8, 0x5b, 0x31, 0x59, 0x30,
	0x2a, 0x79, 0x73, 0x71, 0xc2, 0xc5, 0x85, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0xa1, 0x86,
	0x81, 0xd9, 0x42, 0x22, 0x5c, 0xac, 0x99, 0x79, 0x29, 0xa9, 0x15, 0x60, 0xd3, 0x38, 0x83, 0x20,
	0x1c, 0x90, 0x68, 0x71, 0x49, 0x7e, 0x51, 0xaa, 0x04, 0x33, 0x44, 0x14, 0xcc, 0x49, 0x62, 0x03,
	0x7b, 0xd9, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x82, 0xa7, 0x6a, 0xe5, 0xff, 0x00, 0x00, 0x00,
}
